language: "python"
python:
    - "3.4"
install:
  pip install flake8 pytest pytest-cov
before_script:
  flake8 rsr/
script:
  - echo $PYTHONPATH
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - py.test --cov=rsr --cov-report=term
